security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_HAS_TOKEN: IS_AUTHENTICATED_ANONYMOUSLY

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            simple_preauth:
                authenticator: leo_and_leo_google.authenticator
            access_denied_handler: leo_and_leo_google.access_denied_handler

    access_control:
        - { path: ^/oauthcallback$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_HAS_TOKEN }
