security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        HAS_TOKEN: IS_AUTHENTICATED_ANONYMOUSLY

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        antibiatch:
            pattern: ^/
            anonymous: ~

    access_control:
        - { path: ^/, roles: HAS_TOKEN }
