leo_and_leo_google.google_callback:
    pattern:  /google/oauthcallback
    defaults: { _controller: LeoAndLeoGoogleBundle:Google:callback }

leo_and_leo_google.google_disconnect:
    pattern:  /google/disconnect
    defaults: { _controller: LeoAndLeoGoogleBundle:Google:disconnect }