parameters:
    leo_and_leo_google.authenticator.class: LeoAndLeo\GoogleBundle\Security\Authentication\Authenticator
    leo_and_leo_google.access_denied_handler.class: LeoAndLeo\GoogleBundle\Security\Authorization\AccessDeniedHandler

    leo_and_leo_google.main_list_client.class: LeoAndLeo\GoogleBundle\Service\MainListClient
    leo_and_leo_google.item_list_client.class: LeoAndLeo\GoogleBundle\Service\ItemListClient

services:
    leo_and_leo_google.authenticator:
        class: %leo_and_leo_google.authenticator.class%

    leo_and_leo_google.access_denied_handler:
        class: %leo_and_leo_google.access_denied_handler.class%
        arguments: [@happyr.google.api.client]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    leo_and_leo_google.main_list_client:
        class: %leo_and_leo_google.main_list_client.class%
        arguments: [@happyr.google.api.client, @security.context]

    leo_and_leo_google.item_list_client:
            class: %leo_and_leo_google.item_list_client.class%
            arguments: [@happyr.google.api.client, @security.context]